microsoft/PSRule-vscode

- .vscode/tasks.json
- package-lock.json
- package.json
- src/extension.ts
- Updated package dependencies
> Update package dependencies

- pipeline.build.ps1
> Fix extension CI pipeline

- pipeline.build.ps1
- scripts/pipeline.ps1
- Add task to publish extension to marketplace
> Add extension release task

- README.md
- package.json
- pipeline.build.ps1
- syntaxes/comments.json
- syntaxes/keywords.json
- syntaxes/rule.json
- Add syntax highlighting for built-in keywords
> Add grammars for keywords

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .vscodeignore
- Add GitHub templates for bug, feature and PR.
> Add GitHub templates

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- pipeline.build.ps1
- schemas/PSRule-options.schema.json
- Updated PSRule options schema to v0.4.0 #9
- Fixed CI badge not displaying in VSCode extension tab #8
Fixes #9 
Fixes #8
> Updated PSRule options schema and CI badge #9 #8

- .vscodeignore
- CHANGELOG.md
- docs/example.Rule.ps1
- docs/ps-rule.yaml
- package-lock.json
- package.json
- schemas/PSRule-options.schema.json
- syntaxes/keywords.json
- Updated PSRule options schema to v0.5.0. #12
- Fixed syntax highlighting for keywords that are included in comments. #10
Fixes #12 
Fixes #10 
> Fix syntax highlighting and update options schema #10 #12

- azure-pipelines.yml
- Bump CI pipeline version number to 0.3.0.
> Post v0.2.0 release update

- CHANGELOG.md
- docs/example.Rule.ps1
- snippets/PSRule.json
- syntaxes/comments.json
- syntaxes/keywords.json
- Update highlighting for `Synopsis:` metadata in comments. #16
- Add syntax highlighting and snippet for Recommend keyword. #17
Fixes #16 
Fixes #17
> Update syntax and snippets for PSRule v0.6.0 #16 #17

- CHANGELOG.md
- README.md
- pipeline.build.ps1
- Added build tag for CI process.
- Minor documentation updates.
> Added CI build tag

- CHANGELOG.md
- schemas/PSRule-options.schema.json
- Updated PSRule options schema to v0.7.0. #26
Fixes #26
> Updated PSRule options schema to v0.7.0 #26

- .vscode/extensions.json
- .vscode/tasks.json
- package.json
- Updated dependencies.
- Minor updates to VSCode settings.
> Updates for VSCode editing and dependencies

- CHANGELOG.md
- package-lock.json
- package.json
- schemas/PSRule-options.schema.json
- snippets/powershell.json
- syntaxes/keywords.json
- Add snippet and syntax support for Reason keyword. #32
- Updated PSRule options schema to v0.8.0. #31
Fixes #32 
Fixes #31
> Add Reason keyword and update schema #31 #32

- .azure-pipelines/azure-pipelines.yaml
- Update pipeline version to v0.5.0.
> Update CI pipeline version to v0.5.0

- .azure-pipelines/azure-pipelines.yaml
- pipeline.build.ps1
- Update package paths in pipeline.
> Update package paths for publish

- .azure-pipelines/azure-pipelines.yaml
> Add GitHub release info to CI

- CHANGELOG.md
- ps-project.yaml
- schemas/PSRule-options.schema.json
- Updated PSRule options schema to v0.10.0. #44
Fixes #44 
> Options schema v0.10.0 #44

- .azure-pipelines/azure-pipelines.yaml
> Update CI post v0.7.0

- package-lock.json
- package.json
- Update package dependencies post v0.7.0.
> Update package dependencies post v0.7.0

- CHANGELOG.md
- package-lock.json
- package.json
- schemas/PSRule-options.schema.json
- Updated PSRule options schema to v0.11.0. #49
- Updated dependency versions.
Fixes #49 
> Updated options schema to v0.11.0

- package-lock.json
- package.json
- Update package dependencies.
> Updated package dependencies

- .azure-pipelines/azure-pipelines.yaml
- Updated CI pipeline version to v0.9.0.
> Update pipeline version post v0.8.0

- CHANGELOG.md
- package-lock.json
- package.json
- pipeline.build.ps1
- schemas/PSRule-language.schema.json
- schemas/PSRule-options.schema.json
- Updated PSRule schemas to v0.12.0. #54 
- Updated dependency versions.
Fixes #54 
> Updated PSRule schemas to v0.12.0 #54

- .azure-pipelines/azure-pipelines.yaml
> Update CI post v0.9.0

- package-lock.json
- package.json
- Update vscode dependencies to newer versions.
> Updated vscode dependencies

- CHANGELOG.md
- schemas/PSRule-options.schema.json
- Updated PSRule options schema to v0.14.0. #63
Fixes #63 
> Update options schema to v0.14.0 #63

- CHANGELOG.md
- package-lock.json
- package.json
- schemas/PSRule-options.schema.json
- Updated PSRule options schema to v0.16.0. #68
- Update package dependencies.
Fixes #68
> Updated PSRule options schema to v0.16.0 #68

- .azure-pipelines/azure-pipelines.yaml
- Updated CI version to v0.13.0.
> Updated CI version post v0.12.0 release

- CHANGELOG.md
- schemas/PSRule-language.schema.json
- Updated PSRule resource schema to v0.17.0. #73
Fixes #73 
> Updated resource schema #73

- CHANGELOG.md
- snippets/yaml.json
- Added snippet for ModuleConfig resource. #75
Fixes #75 
> Added snippet for ModuleConfig resource #75

- package-lock.json
- package.json
- Updated eslint package dependencies.
> Updated eslint dependencies

- .azure-pipelines/azure-pipelines.yaml
- Updated CI pipeline version to v0.14.0.
> Post v0.13.0 CI update

- CHANGELOG.md
- schemas/PSRule-options.schema.json
- Updated options schema to include `requires` property.
Fixes #87
> Update options schema to v0.19.0 #87

- .gitignore
- Exclude reports for git ignore.
> Exclude reports from git

- .azure-pipelines/azure-pipelines.yaml
- Updated CI version to v0.15.0
> Update CI version post v0.14.0

- .azure-pipelines/azure-pipelines.yaml
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- package.json
- ps-project.yaml
- Updated default branch to main.
> Update default branch name

- CHANGELOG.md
- schemas/PSRule-language.schema.json
- schemas/PSRule-options.schema.json
- Updated PSRule options schema to v0.20.0. #106
- Updated PSRule resource schema to v0.20.0. #107
Fixes #106 
Fixes #107 
> Updated schemas to latest versions #106 #107

- .azure-pipelines/azure-pipelines.yaml
- Updated the CI pipeline version to v0.16.0.
> Update CI pipeline version

- CHANGELOG.md
- schemas/PSRule-language.schema.json
- schemas/PSRule-options.schema.json
- Updated PSRule options schema to v0.21.0. #135
- Updated PSRule resource schema to v0.21.0. #134
Fixes #134 
Fixes #135 
> Updated PSRule schemas #135 #134

- .azure-pipelines/pipeline-deps.ps1
- .github/workflows/analyze.yaml
- .ps-rule/OpenSource.Rule.ps1
- .vscode/tasks.json
- docs/example.Rule.ps1
- pipeline.build.ps1
- ps-rule.yaml
- src/extension.ts
- Add PSRule rule for validating the repository.
> Added repository validation rules

- .azure-pipelines/azure-pipelines.yaml
- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .ps-rule/OpenSource.Rule.ps1
- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- README.md
- SECURITY.md
- SUPPORT.md
- package.json
- ps-project.yaml
- Updated repository files and links to point to Microsoft org.
- Added OSS files.
Fixes #152
> Migrate repository to Microsoft GitHub org #152

- CHANGELOG.md
- schemas/PSRule-language.schema.json
- schemas/PSRule-options.schema.json
- Updated PSRule options schema to support conventions. #199
Fixes #199 
> Updated PSRule options schema to support conventions #199

- .azure-pipelines/azure-pipelines.yaml
- .eslintrc.json
- .prettierrc
- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
- CHANGELOG.md
- README.md
- SUPPORT.md
- package-lock.json
- package.json
- pipeline.build.ps1
- src/consts.ts
- src/extension.ts
- src/logger.ts
- src/test/runTest.ts
- src/test/suite/index.ts
- tsconfig.json
- Split extension into two release channels, _preview_ and _stable_. #150
> Split extension into two release channels #150

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/jobs/build-channel.yaml
- .azure-pipelines/jobs/publish-channel.yaml
- .azure-pipelines/jobs/test.yaml
- .azure-pipelines/jobs/testContainer.yaml
- pipeline.build.ps1
- Updated CI pipeline with unit tests.
> Update CI pipeline

- .markdownlint.json
- .vscode/tasks.json
- CHANGELOG.md
- package-lock.json
- package.json
- pipeline.build.ps1
- src/extension.ts
- Preview channel appears as _PSRule (Preview)_, with stable appearing as _PSRule_. #229
Fixes #229 
> Update display name for channel #229

- CHANGELOG.md
- schemas/PSRule-language.schema.json
- schemas/PSRule-options.schema.json
- Added support for `input.ignoreGitPath` option. #231
Fixes #231 
> Add support for input.ignoreGitPath option #231

- .azure-pipelines/azure-pipelines.yaml
- pipeline.build.ps1
- Updated pipeline for preview release post v1.
> Update pipeline post release

- pipeline.build.ps1
- Pipeline update to fix preview publish.
> Fix preview publish

- .azure-pipelines/azure-pipelines.yaml
- CHANGELOG.md
- pipeline.build.ps1
> Update CI versioning

- CHANGELOG.md
- package-lock.json
- package.json
- src/tasks.ts
- Added `$PSRule` problem matcher for analysis tasks. #234
- Source locations for rules failures are detected when using the `VisualStudioCode` style.
Fixes #234 
> Added PSRule problem matcher

- package-lock.json
- package.json
- Bump dev dependencies to newer versions.
> Bump dev dependencies

- package-lock.json
- package.json
- Update dev packages to the latest versions.
> Bump dev packages

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/jobs/test.yaml
- .azure-pipelines/jobs/testContainer.yaml
- Updated CI pipeline images to latest versions.
> Updated CI pipeline images

- CHANGELOG.md
- schemas/PSRule-language.schema.json
- schemas/PSRule-resources.schema.json
Fixes #574.
Just queueing up this PR for when we want this included in the extension. 
> Added suppression group schema from PSRule

- CHANGELOG.md
- snippets/json.json
- snippets/yaml.json
> Added resource snippets for Suppression Groups

- .github/workflows/schema.yaml
- CHANGELOG.md
> Added schema sync workflow

- .github/workflows/analyze.yaml
- .vscode/extensions.json
- schemas/PSRule-language.schema.json
- schemas/PSRule-options.schema.json
- schemas/PSRule-resources.schema.json
- Added GitHub code scanning in additional to existing security scans to CI pipeline.
> Added GitHub code scanning

- .azure-pipelines/azure-pipelines.yaml
- pipeline.build.ps1
- ps-rule.yaml
> Prepare CI for v2 release

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/jobs/test.yaml
- CHANGELOG.md
- docs/example.Rule.ps1
- package-lock.json
- package.json
- src/test/runTest.ts
- src/test/suite/configuration.test.ts
- syntaxes/comments.json
- syntaxes/keywords.json
- syntaxes/rule.json
- Fixed change syntax highlighting on PowerShell files.
Fixes #495
> Fixes for syntax highlighting #495

- .vscode/settings.json
- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/configuration.ts
- src/extension.ts
- src/powershell.ts
- src/tasks.ts
- src/test/runTest.ts
- src/test/suite/configuration.test.ts
- Improved compatibility with PowerShell extension.
- Supports either PowerShell or PowerShell Preview installed for running tasks.
- If PowerShell extension is not installed or enabled, basic functions are still available.
Fixes #607 
> Improved PowerShell extension support #607

- .github/ISSUE_TEMPLATE/bug_report.md
- CHANGELOG.md
What's changed since v1.7.0:
- PSRule v2.0.0 support:
- Added resource snippets for Suppression Groups. #588
- Updated schema to support Suppression Groups. #574
- Updated schema to support convert and case sensitive properties.
#626
#630
- Updated schema to support improved validation of resource names. #638
- Added resource snippets for JSON and JSONC files. #477
- Improved compatibility with PowerShell extension. #607
- Supports either PowerShell or PowerShell Preview installed for running tasks.
- If PowerShell extension is not installed or enabled, basic functions are still available.
- Engineering:
- Added workflow to sync PSRule schemas. #592
- Bump vscode engine to v1.66.0. #653
- Bug fixes:
- Fixed change syntax highlighting on PowerShell files. #495
> Release v2.0.0

- .azure-pipelines/azure-pipelines.yaml
- CHANGELOG.md
> Bump CI and change log

- CHANGELOG.md
> Bump change log

- .github/ISSUE_TEMPLATE/bug_report.md
- CHANGELOG.md
What's changed since v2.1.0:
- Added command to create options file by @BernieWhite.
[#662](https://github.com/microsoft/PSRule-vscode/issues/662)
- From the command palette choose _PSRule: Create options file_.
- Engineering:
- Bump vscode engine to v1.68.1.
[#753](https://github.com/microsoft/PSRule-vscode/pull/753)
- Bump vscode-languageclient from v8.0.1.
[#703](https://github.com/microsoft/PSRule-vscode/pull/703)
- Updated PSRule schema files.
[#743](https://github.com/microsoft/PSRule-vscode/pull/743)
> Release v2.2.0

- .vscode/settings.json
- Added setting for editing in VSCode.
> Add Branch Protection setting for VSCode

- README.md
> Minor updates to documentation

- CHANGELOG.md
- package.json
- snippets/github-snippets.json
- snippets/pipelines-snippets.json
- Added starter pipeline snippet for Azure Pipelines.
Fixes #851 
> Added starter Azure Pipeline snippet

- .github/dependabot.yml
- .github/workflows/analyze.yaml
- .github/workflows/schema.yaml
- .gitignore
- .vscode/settings.json
- .vscodeignore
- scripts/schemas.psm1
- Update workflows and VSCode settings.
> Updated automation for schema bump

- CHANGELOG.md
- schemas/PSRule-language.schema.json
Additional updates to language schema.
> Updates to schema

- .vscode/launch.json
- CHANGELOG.md
- package.json
- src/configuration.ts
- src/extension.ts
- src/test/runTest.ts
- src/test/suite/configuration.test.ts
- CodeLens for open or editing documentation for a rule is now generally available.
Fixes #1139 
> Promoted doc codelens to GA #1139

- CHANGELOG.md
What's changed since v2.8.0:
- New features:
- Getting started walkthrough in Visual Studio Code is now generally available by @BernieWhite
[#1099](https://github.com/microsoft/PSRule-vscode/issues/1099)
- CodeLens for open or editing documentation for a rule is now generally available by @BernieWhite
[#1139](https://github.com/microsoft/PSRule-vscode/issues/1139)
- Added configuration to tune logging for excluded or suppressed rules by @BernieWhite.
[#1068](https://github.com/microsoft/PSRule-vscode/issues/1068)
- Use these options to reduce output noise when testing in Visual Studio Code.
- The `PSRule.execution.ruleExcluded` setting configures excluded rules.
- The `PSRule.execution.ruleSuppressed` setting configures suppressed rules.
- Add running analysis to getting started …
> Release v2.9.0

- .vscode/launch.json
- package.json
- pipeline.build.ps1
- src/configuration.ts
- src/extension.ts
- src/tasks.ts
- src/test/suite/configuration.test.ts
- src/test/suite/extension.test.ts
Cleanup old v2 configuration options.
> Clean up old configuration options

- .vscode/tasks.json
- CHANGELOG.md
- package-lock.json
- package.json
- pipeline.build.ps1
- src/commands/restore.ts
- src/configuration.ts
- src/extension.ts
- src/tasks.ts
- src/utils.ts
- Automatically acquire and install PSRule CLI.
- Extension will automatically download and install PSRule CLI when it is not available.
- Installing PSRule PowerShell module is no longer required for the extension to work.
Fixes #1315
> Acquire and installl CLI #1315

- GitVersion.yml
> Bump GitVersion.yml

- CHANGELOG.md
- schemas/PSRule-lock.schema.json
> Update to schemas

- .github/workflows/build.yaml
- package-lock.json
- package.json
- pipeline.build.ps1
- src/extension.ts
- Update the package name used for marketplace to address reserved name.
> Update package name

- .vscode/extensions.json
- .vscode/settings.json
- dotnet/PSRule.EditorServices/ClientBuilder.cs
- dotnet/PSRule.EditorServices/PSRule.EditorServices.csproj
- dotnet/PSRule.EditorServices/Program.cs
- dotnet/PSRule.EditorServices/Properties/launchSettings.json
- dotnet/PSRule.EditorServices/packages.lock.json
- package.json
- src/commands/restore.ts
- src/configuration.ts
- src/tasks.ts
Added server tooling for support towards #225
> Added server tooling #225

- .devcontainer/devcontainer.json
- .github/dependabot.yml
- .vscode/extensions.json
- Update the dev container configuration.
> Improve dev container config

- schemas/PSRule-options.schema.json
Bump schemas/PSRule-options.schema.json
> Bump schemas

- .github/dependabot.yml
- dotnet/PSRule.EditorServices/packages.lock.json
> Group linting dependencies

- docs/Example.Rule.jsonc
- docs/example.Rule.ps1
- schemas/PSRule-language.schema.json
- schemas/PSRule-lock.schema.json
- src/docLens.ts
- src/extension.ts
- src/utils.ts
> Cleanup and schema updates

- .vscode/settings.json
- .vscodeignore
- CHANGELOG.md
- extension.md
- package.json
Updated packaging and readme to reflect repository changes.
> Update packaging for V2
