microsoft/PSRule-vscode

CHANGELOG.md
docs/example.Rule.yaml
package.json
schemas/PSRule-language.schema.json
schemas/PSRule-options.schema.json
snippets/yaml.json
syntaxes/yaml-comments.json

- Added PSRule resource schema. #39
- Updated PSRule options schema to v0.9.0. #38
- Added snippet for baseline resource. #40
- Added highlighting for `Synopsis:` resource comments. #41
Fixes #39 
Fixes #38 
Fixes #40 
Fixes #41 

Add support for v0.9.0 features #38 #39 #40 #41

---

.azure-pipelines/azure-pipelines.yaml

- Updated CI pipeline images to use latest versions of Ubuntu and MacOS.
- Bumped CI pipeline version to v0.12.0.

Update CI pipeline images

---

CHANGELOG.md
docs/example.Rule.ps1
docs/example.Rule.yaml
schemas/PSRule-language.schema.json
schemas/PSRule-options.schema.json
snippets/yaml.json

- Added support for selectors. #206
- Updated options and language schema to support `binding.preferTargetInfo` option. #207
- Updated language schema to add `apiVersion` property. #208
Fixes #206 
Fixes #207 
Fixes #208 

Added support for selectors #206 #207 #208

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
README.md

What's changed since v0.18.0:
- Added support for `input.ignoreGitPath` option. #231
- Added feature documentation. #151
- Engineering:
- Split extension into two release channels, _Preview_ and _Stable_. #150
- Preview channel appears as _PSRule (Preview)_, with stable appearing as _PSRule_. #229
- Improved extension performance and size by bundling. #222

Release v1.0.0

---

CHANGELOG.md
package.json
src/extension.ts

- Preview channel will notify that a stable version is available. #235
Fixes #235 

Notify preview channel of stable channel #235

---

CHANGELOG.md
schemas/PSRule-options.schema.json

- Added PSRule options schema support updates.
- Added `Output.Banner` option. #264
- Improved validation for the requires option. #265
- Added support for new style options `VisualStudioCode` and `Detect`. #266
Fixes #264 
Fixes #265 
Fixes #266 

Options schema updates #264 #265 #266

---

CHANGELOG.md
schemas/PSRule-language.schema.json
schemas/PSRule-options.schema.json

- Added string selector support to language schema. #327
- Updated options schema to support PSRule v1.5.0. #328
Fixes #327 
Fixes #328 

Updated options and language schema #327 #328

---

CHANGELOG.md
package.json
schemas/PSRule-language.schema.json
schemas/PSRule-options.schema.json
snippets/github-actions.json
snippets/yaml.json

- Added YAML Rule support to language schema. #361
- Added starter snippet for GitHub Actions workflow. #362
- Updated options schema to support `include` option within PSRule v1.6.0. #363
Fixes #361 
Fixes #362 
Fixes #363

Added PSRule v1.6.0 improvements #361 #362 #363

---

CHANGELOG.md
schemas/PSRule-options.schema.json

- Added options schema to support options introduced in PSRule v1.7.0.
- Added support for `Input.IgnoreRepositoryCommon`, `Output.Footer`, and `Rule.IncludeLocal`.
Fixes #395

Added options for PSRule v1.7.0 #395

---

CHANGELOG.md
docs/Example.Rule.jsonc
package.json
schemas/PSRule-language.schema.json
schemas/PSRule-resources.schema.json

- Added `Rule.Baseline` option configuration the default baseline with module configuration. #475
- Added support for resources within `.Rule.json`, `.Rule.jsonc`, and `.Rule.yml` files. #476
- Configured workspace trust. #304
- Currently the extension relies on PowerShell which only works when the workspace is trusted.
Fixes #475 
Fixes #476 
Fixes #304 

Added JSON resource support #475 #476 #304

---

.github/workflows/schema.yaml

Ensuring only `*.schema.json` files are added and commited. 
Caught this issue in this test PR: https://github.com/microsoft/PSRule-vscode/pull/599, where PSRule was being added as a submodule. 

Fix issue with schema workflow adding PSRule submodule

---

.vscode/tasks.json
CHANGELOG.md
README.md
package.json
ps-rule.yaml
src/configuration.ts
src/tasks.ts
src/test/suite/configuration.test.ts

- Added configuration option for baseline.
- Configure the default baseline in the extension settings.
- Baseline can be overridden using the `baseline` property on a PSRule task.
Fixes #770

Added baseline option #770

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md

What's changed since v2.2.0:
- Added configuration option for baseline by @BernieWhite.
[#770](https://github.com/microsoft/PSRule-vscode/issues/770)
- Configure the default baseline in the extension settings.
- Baseline can be overridden using the `baseline` property on a PSRule task.
- Engineering:
- Updated PSRule schema files.
[#767](https://github.com/microsoft/PSRule-vscode/pull/767)
- Bump vscode-languageclient v8.0.2.
[#777](https://github.com/microsoft/PSRule-vscode/pull/777)
- Bumps vscode engine to v1.69.1.
[#797](https://github.com/microsoft/PSRule-vscode/pull/797)

Release v2.3.0

---

CHANGELOG.md
src/extension.ts

- Added a warning when multiple channels are installed.
Fixes #870 

Added a warning for multi-channel install #870

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

What's changed since v2.5.0:
- Engineering:
- Updated PSRule schema files.
[#920](https://github.com/microsoft/PSRule-vscode/pull/920)
- Bumps vscode engine to v1.73.1.
[#922](https://github.com/microsoft/PSRule-vscode/pull/922)
- Bump vsce to v2.14.0.
[#916](https://github.com/microsoft/PSRule-vscode/pull/916)
- Bumps @vscode/test-electron to v2.2.0.
[#902](https://github.com/microsoft/PSRule-vscode/pull/902)
- Bump typescript to v4.9.3.
[#925](https://github.com/microsoft/PSRule-vscode/pull/925)

Release v2.6.0

---

CHANGELOG.md

What's changed since v2.7.0:
- Engineering:
- Updated PSRule schema files.
[#1060](https://github.com/microsoft/PSRule-vscode/pull/1060)
[#1062](https://github.com/microsoft/PSRule-vscode/pull/1062)
- Bump vscode engine to v1.76.0.
[#1036](https://github.com/microsoft/PSRule-vscode/pull/1036)
- Bump mocha to v10.2.0.
[#957](https://github.com/microsoft/PSRule-vscode/pull/957)
- Bump fs-extra to v11.1.1.
[#1058](https://github.com/microsoft/PSRule-vscode/pull/1058)
- Bump glob to v8.1.0.
[#990](https://github.com/microsoft/PSRule-vscode/pull/990)
- Bump typescript to v5.0.2.
[#1053](https://github.com/microsoft/PSRule-vscode/pull/1053)
- Bump minimist to v1.2.8.
[#1014](https://github.com/microsoft/PSRule-vscode/pull/1014)
- Bump vscode-languageclient to v8.1.0. …

Release v2.8.0

---

CHANGELOG.md
package-lock.json
package.json

- Bump and rename vsce package to `@vscode/vsce` v2.19.0.
Fixes #1090 

Bump vscode/vsce to v2.19.0 #1090

---

.vscode/launch.json
CHANGELOG.md
README.md
package.json
src/configuration.ts
src/tasks.ts
src/test/suite/configuration.test.ts

- Added configuration to tune logging for excluded or suppressed rules by @BernieWhite.
- Use these options to reduce output noise when testing in Visual Studio Code.
- The `PSRule.execution.ruleExcluded` setting configures excluded rules.
- The `PSRule.execution.ruleSuppressed` setting configures suppressed rules.
Fixes #1068 

Add config for excluded and suppressed rules #1068

---

CHANGELOG.md
README.md
package.json
src/configuration.ts
src/tasks.ts
src/test/suite/configuration.test.ts

- Added support for new unprocessed object option.
- The `PSRule.execution.unprocessedObject` setting configures what happens when objects are not processed.
- The `PSRule.execution.notProcessedWarning` setting has been deprecated inline with PSRule support.
- For more information see [deprecations](https://aka.ms/ps-rule/deprecations#execution-options).
Fixes #1127 

Added support for unprocessed object option #1127

---

CHANGELOG.md
src/extension.ts

- Fixed notification of preview version.
Fixes #1324

Fix notification for preview #1324
